// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"Pheidippides/internal/biz"
	"Pheidippides/internal/conf"
	"Pheidippides/internal/data"
	"Pheidippides/internal/server"
	"Pheidippides/internal/service"
	"Pheidippides/pkg/infra"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

// newApp init kratos application.
func initApp(confServer *conf.Server, redis *conf.Redis) (*kratos.App, error) {
	queueType := data.NewRedisType()
	queue := infra.NewQueue(queueType, redis)
	pheidiQueue := data.NewPeidiQueue(queue)
	pheidiUseCase := biz.NewPheidiUseCase(pheidiQueue)
	pheidiQueueService := service.NewPheidiQueueService(pheidiUseCase)
	grpcServer := server.NewGRPCServer(confServer, pheidiQueueService)
	app := newApp(grpcServer)
	return app, nil
}
